const components = [
    { name: "Accordion", link: "/accordion-docs" },
    { name: "Bento", link: "./bento-docs" },
    { name: "Breadcrumb", link: "./breadcrumb-docs" },
    { name: "Button", link: "./button-docs" },
    { name: "Card", link: "./card-docs" },
    { name: "Carousel", link: "./carousel-docs" },
    { name: "Checkbox", link: "./checkbox-docs" },
    { name: "Comment", link: "./comment-docs" },
    { name: "Dropdown", link: "./dropdown-docs" },
    { name: "Feed", link: "./feed-docs" },
    { name: "Form", link: "./form-docs" },
    { name: "Menu", link: "./menu-docs" },
    { name: "Icon", link: "./icon-docs" },
    { name: "Input", link: "./input-docs" },
    { name: "Loader", link: "./loader-docs" },
    { name: "Modal", link: "./modal-docs" },
    { name: "Notification", link: "./notification-docs" },
    { name: "Pagination", link: "./pagination-docs" },
    { name: "Picker", link: "./picker-docs" },
    { name: "Progress Bar", link: "./progressBar-docs" },
    { name: "Radio Buttons", link: "./radio-buttons-docs" },
    { name: "Search Field", link: "./search-field-docs" },
    { name: "Slider", link: "./slider-docs" },
    { name: "Stepper", link: "./stepper-docs" },
    { name: "Tags", link: "./tags-docs" },
    { name: "Tabs", link: "./tabs-docs" },
    { name: "Tab Bar", link: "./tab-bar-docs" },
    { name: "Tooltip", link: "./tooltip-docs" },
    { name: "Toggle", link: "./toggle-docs" },
];

export default components;
