const components = [
    { name: "Accordion", link: "/accordion" },
    { name: "Bento", link: "./bento" },
    { name: "Breadcrumb", link: "./breadcrumb" },
    { name: "Button", link: "./button" },
    { name: "Card", link: "./card" },
    { name: "Carousel", link: "./carousel" },
    { name: "Checkbox", link: "./checkbox" },
    { name: "Comment", link: "./comment" },
    { name: "Dropdown", link: "./dropdown" },
    { name: "Feed", link: "./feed" },
    { name: "Form", link: "./form" },
    { name: "Menu", link: "./menu" },
    { name: "Icon", link: "./icon" },
    { name: "Input", link: "./input" },
    { name: "Loader", link: "./loader" },
    { name: "Modal", link: "./modal" },
    { name: "Notification", link: "./notification" },
    { name: "Pagination", link: "./pagination" },
    { name: "Picker", link: "./picker" },
    { name: "Progress Bar", link: "./progressBar" },
    { name: "Radio Buttons", link: "./radio-buttons" },
    { name: "Search Field", link: "./search-field" },
    { name: "Slider", link: "./slider" },
    { name: "Stepper", link: "./stepper" },
    { name: "Tags", link: "./tags" },
    { name: "Tabs", link: "./tabs" },
    { name: "Tab Bar", link: "./tab-bar" },
    { name: "Tooltip", link: "./tooltip" },
    { name: "Toggle", link: "./toggle" },
];

export default components;
